import { VideoData } from '../types';

export const fetchSoraVideo = async (url: string): Promise<VideoData> => {
    if (!url.includes('sora.chatgpt.com')) {
        throw new Error("Vui lòng nhập link Sora hợp lệ (Ví dụ: https://sora.chatgpt.com/p/...)");
    }

    const proxies = [
        (u: string) => `https://corsproxy.io/?${encodeURIComponent(u)}`,
        (u: string) => `https://api.allorigins.win/raw?url=${encodeURIComponent(u)}`
    ];

    let rawHtml: string = "";

    // Step 1: Fetch HTML via Proxies
    for (const createProxyUrl of proxies) {
        try {
            const proxyUrl = createProxyUrl(url);
            const response = await fetch(proxyUrl);
            
            if (!response.ok) continue;
            
            const html = await response.text();
            
            // Basic validation: ensure we got some HTML-like content
            if (html && html.length > 100 && (html.includes('<') || html.includes('sora'))) {
                 rawHtml = html;
                 break; 
            }
        } catch (e) {
            console.warn("Proxy attempt error:", e);
        }
    }

    if (!rawHtml) {
        throw new Error("Không thể kết nối đến máy chủ Sora. Vui lòng thử lại sau hoặc kiểm tra đường truyền.");
    }

    try {
        // Step 2: Advanced Parsing Strategy
        
        // 2a. Normalize HTML (fix escaped slashes common in JSON data which breaks simple Regex)
        // e.g. "https:\/\/cdn..." -> "https://cdn..."
        const cleanHtml = rawHtml.replace(/\\\//g, '/');
        
        // 2b. DOM Parser for Standard Meta Tags
        const parser = new DOMParser();
        const doc = parser.parseFromString(cleanHtml, 'text/html');

        let videoUrl = doc?.querySelector('meta[property="og:video"]')?.getAttribute('content') ||
                       doc?.querySelector('meta[property="og:video:url"]')?.getAttribute('content') ||
                       doc?.querySelector('meta[property="og:video:secure_url"]')?.getAttribute('content') ||
                       doc?.querySelector('meta[property="twitter:player:stream"]')?.getAttribute('content');

        // 2c. JSON-LD or Next.js Data Search (Regex)
        if (!videoUrl) {
            // Pattern 1: Look for "url":"..." or "contentUrl":"..." containing .mp4
            const jsonPatterns = [
                /"(?:contentUrl|url|src)"\s*:\s*"(https?:\/\/[^"]+?\.mp4(?:\?[^"]*)?)"/i,
                /"(https?:\/\/cdn\.openai\.com\/[^"]+?\.mp4(?:\?[^"]*)?)"/i
            ];

            for (const pattern of jsonPatterns) {
                const match = cleanHtml.match(pattern);
                if (match && match[1]) {
                    videoUrl = match[1];
                    break;
                }
            }
        }

        // 2d. Brute Force .mp4 Search
        if (!videoUrl) {
            // Find any string starting with http and ending with mp4 inside quotes
            const mp4Regex = /"(https?:\/\/[^"]+?\.mp4(?:\?[^"]*)?)"/i;
            const match = cleanHtml.match(mp4Regex);
            if (match && match[1]) {
                videoUrl = match[1];
            }
        }
        
        // Cleanup URL if found (unicode escapes usually like \u0026 -> &)
        if (videoUrl) {
            videoUrl = videoUrl.replace(/\\u0026/g, '&');
        }

        // Metadata extraction
        const thumbnail = doc?.querySelector('meta[property="og:image"]')?.getAttribute('content') || 
                          'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/1024px-ChatGPT_logo.svg.png';
        
        let description = doc?.querySelector('meta[property="og:description"]')?.getAttribute('content') || 
                            doc?.querySelector('meta[name="description"]')?.getAttribute('content') || 
                            'Sora Video';

        // Fallback title/description
        const title = doc?.querySelector('meta[property="og:title"]')?.getAttribute('content') || 'Video generated by Sora';
        if (description === 'Sora Video' && title !== 'Video generated by Sora') {
            description = title;
        }

        if (!videoUrl) {
            console.log("Debug: No video URL found in content length:", rawHtml.length);
            throw new Error("Không tìm thấy link video. Có thể video chưa được công khai hoặc đã bị xóa.");
        }

        return {
            id: url.split('/').pop() || 'sora_' + Date.now(),
            title: description, 
            author: 'OpenAI Sora',
            avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/1024px-ChatGPT_logo.svg.png', 
            thumbnail: thumbnail,
            stats: {
                views: 'N/A',
                likes: 'N/A',
                comments: 'N/A'
            },
            downloads: {
                noWatermark: videoUrl,
                watermark: '', 
                mp3: '' 
            }
        };

    } catch (e: any) {
        console.error("Sora Parse Error:", e);
        throw new Error(e.message || "Lỗi khi phân tích dữ liệu từ Sora.");
    }
}